name: BlogCI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      -name: Download Source file
       uses: actions/checkout@v2
       with:
         ref: sources
      -name: Prepare Node env
       uses: actions/setup-node@v1
       with:
         node-version:"16.6.2"
      -name: Set Env
       env:
         BLOG_ACCESS_TOKEN: ${{ secrets.BLOG_ACCESS_TOKEN }}
       run:
         git config --global user.name 'Manwcy'
         git config --global user.email 'junnan0ma@gmail.com'
         sed -i "s/BLOG_ACCESS_TOKEN/$BLOG_ACCESS_TOKEN/g" ./_config.yml
      -name: Hexo
       run: 
         npm i -g Hexo-cli
         npm i
         Hexo clean && Hexo g && Hexo d
