name: BlogCI

on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Download Source file
      uses: actions/checkout@v2
      with:
        ref: sources # Specify the name of the branch where you store Hexo source files
    - name: Prepare Node env
      uses: actions/setup-node@v1
      with:
        node-version: "16.6.2" # This corresponds to your own nodejs version (10.12 tested well)
    - name: Set Env
      env: 
        BLOG_ACCESS_TOKEN: ${{ secrets.BLOG_ACCESS_TOKEN }}  
      run: |
        git config --global user.name 'Manwcy' # github用户名
        git config --global user.email 'junnan0ma@gmail.com' # github邮箱
        sed -i "s/BLOG_ACCESS_TOKEN/$BLOG_ACCESS_TOKEN/g" ./_config.yml
    - name: Hexo
      run: |
        npm i -g Hexo-cli
        npm i
        Hexo clean && Hexo g && Hexo d
